name: sass_builder
version: 2.1.1

authors:
- Luis Vargas <luisvargastijerino@gmail.com>
- Kevin Moore <kevmoo@github.com>
- Nicholas Shahan <nshahan@github.com>

homepage: https://github.com/dart-league/sass_builder
description: Transpile sass files using the "build" package.

environment:
  sdk: '>=2.0.0-dev.51 <3.0.0'

dependencies:
  build: ^1.0.0
  build_config: ^0.3.0
  path: ^1.0.0
  sass: ^1.0.0

dev_dependencies:
  build_test: ^0.10.0
  test: ^1.0.0